language: python
dist: xenial
python:
- 3.4
- 3.5
- 3.6
- 3.7
install: pip install tox
script:
- tox -r -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d . | sed -e 's/pypypy/pypy/')
- tox -e lint
- tox -e docs
after_failure: cat .tox/log/tox-*.log
deploy:
  provider: pypi
  user: n8henrie
  password:
    secure: e7PRlElUj+5p45rwxCsh87QFBhWn7GpE0+xZln+SEHgM+LYd6+bKQR8gsY9oB8hC3FNQOZz12k6yUazDhF454iNdTkG2vKjk2Vd7OqeRyvVteE+pj6/xGLRHMJPxdRcUj7zDvPlk1AMf8SsY9/VE9AgWBcKPbAsI5zEk6RIOWVDIrmEptlc2mT0/qVu08c+Ddu19CM3rvT/HTDPFfWwhBfQkWEjVepng74i1R66GEcmifc4uKZGjuFTqgwgtXIlS6smcwBSii5macLtxwCZw0YgI9+n+94DPMrDhw1gK115vsWa+fUfxqfP0Wk8aSxbxxQD2H5ihNMHyV2YNC+zLRPMci0SOl2/UUXR7cncfx5spTGtsqpf0s4nEVHxs/realcTZdXnlCq9hcuCuPtBGiDFQ8D12sI7K8u6ql2z1UzUweEOql1LRHbUSafcavxiQ9NCfo6/QNdGpLX8funxQZxbx3EjgkOQZ2NnJxQqK/BLRjEr+P5rZlUgOxh1C4HAa64ghtYyjmdv2tW7X0PJfJE77Mvh8wi26Rxdm7eowpXf0gX/zWYcq3xTNbeq1CI+BgaZsqT56Q7W38iUo9fgwYD+v0IdNETcjy+PmULm3HMoQJmOo2DTRN/8T0dSvXtX7600LGNGe3tPMYkbAaWkf7dtnmjo5uHbW7jKIjKmYxP8=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    repo: n8henrie/nmfishingreport
  skip_cleanup: true
  skip_existing: true
