sudo: required
dist: trusty
language: python

python: "3.5"
env:
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy3

install: pip install tox

script: tox
after_failure: cat .tox/log/tox-*.log
